[package]
name = "benchmark"
version = "0.1.0"
edition = "2024"

[dependencies]
chrono = "0.4.44"
config = "0.15.22"
csv = "1.4.0"
env_logger = "0.11.10"
futures = "0.3.32"
log = "0.4.29"
omnipaxos = { path = "../omnipaxos", features = [
  "serde",
  "toml_config",
  "logging",
] }
rand = "0.10.1"
serde = { version = "1.0.228", features = ["derive"] }
serde_json = "1.0.149"
slog = "2.7.0"
slog-term = "2.9.0"
slog-async = "2.7.0"
tokio = { version = "1.52.1", features = ["full"] }
tokio-serde = { version = "0.9.0", features = ["bincode"] }
tokio-util = { version = "0.7.18", features = ["codec"] }

[features]
adaptive = ["omnipaxos/adaptive"]

[[bin]]
name = "client"
path = "src/client/main.rs"

[[bin]]
name = "server"
path = "src/server/main.rs"

[[bin]]
name = "daemon"
path = "src/daemon.rs"
