x-common-server-variables: &common-server-variables
  RUST_LOG: "info"
  SERVER_CONFIG_FILE: "/app/server-config.toml"
  CLUSTER_CONFIG_FILE: "/app/cluster-config.toml"

services:
  # --- SERVERS ---
  s1:
    image: network-daemon
    build: { context: ./, dockerfile: daemon.dockerfile }
    container_name: s1
    environment:
      <<: *common-server-variables
      NODE_ID: "1"
    volumes:
      - ./configs/server_1.toml:/app/server-config.toml
      - ./configs/cluster.toml:/app/cluster-config.toml
      - s1-ipc:/tmp

  s1-server:
    image: server-adaptive
    build: { context: ./, dockerfile: server_adaptive.dockerfile }
    container_name: s1-server
    environment:
      <<: *common-server-variables
      NODE_ID: "1"
    volumes:
      - ./configs/server_1.toml:/app/server-config.toml
      - ./configs/cluster.toml:/app/cluster-config.toml
      - ./results/:/app/results/
      - s1-ipc:/tmp
    depends_on:
      - s1

  s2:
    image: network-daemon
    container_name: s2
    environment:
      <<: *common-server-variables
      NODE_ID: "2"
    volumes:
      - ./configs/server_2.toml:/app/server-config.toml
      - ./configs/cluster.toml:/app/cluster-config.toml
      - s2-ipc:/tmp

  s2-server:
    image: server-adaptive
    container_name: s2-server
    environment:
      <<: *common-server-variables
      NODE_ID: "2"
    volumes:
      - ./configs/server_2.toml:/app/server-config.toml
      - ./configs/cluster.toml:/app/cluster-config.toml
      - ./results/:/app/results/
      - s2-ipc:/tmp
    depends_on:
      - s2

  s3:
    image: network-daemon
    container_name: s3
    environment:
      <<: *common-server-variables
      NODE_ID: "3"
    volumes:
      - ./configs/server_3.toml:/app/server-config.toml
      - ./configs/cluster.toml:/app/cluster-config.toml
      - s3-ipc:/tmp

  s3-server:
    image: server-adaptive
    container_name: s3-server
    environment:
      <<: *common-server-variables
      NODE_ID: "3"
    volumes:
      - ./configs/server_3.toml:/app/server-config.toml
      - ./configs/cluster.toml:/app/cluster-config.toml
      - ./results/:/app/results/
      - s3-ipc:/tmp
    depends_on:
      - s3

  # --- CLIENTS ---
  c1:
    image: client
    build: { context: ./, dockerfile: client.dockerfile }
    container_name: c1
    environment:
      RUST_LOG: "info"
      CONFIG_FILE: "/app/client-config.toml"
      NODE_ID: "1"
    volumes:
      - ./configs/client_1.toml:/app/client-config.toml
      - ./results/:/app/results/

  c2: &client-base
    image: client
    container_name: c2
    environment:
      RUST_LOG: "info"
      CONFIG_FILE: "/app/client-config.toml"
      NODE_ID: "2"
    volumes:
      - ./configs/client_2.toml:/app/client-config.toml
      - ./results/:/app/results/

  c3:
    <<: *client-base
    container_name: c3
    environment:
      RUST_LOG: "info"
      CONFIG_FILE: "/app/client-config.toml"
      NODE_ID: "3"
    volumes:
      - ./configs/client_3.toml:/app/client-config.toml
      - ./results/:/app/results/

# For shared sockets
volumes:
  s1-ipc:
  s2-ipc:
  s3-ipc:
